import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./ui/Providers";

export const metadata: Metadata = {
  title: "TB AniManga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="text-8xl">Hola Animanga</div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
